services:
  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - bookmark_management

  bookmark_service:
    image: bookmark_service:test
    container_name: bookmark
    ports:
      - "8080:8080"
    environment:
      - REDIS_ADDR=redis:6379
    networks:
      - bookmark_management

networks:
  bookmark_management:
    driver: bridge
    