// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// Bookmark is an autogenerated mock type for the Bookmark type
type Bookmark struct {
	mock.Mock
}

// CheckRedisConnection provides a mock function with given fields: ctx
func (_m *Bookmark) CheckRedisConnection(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for CheckRedisConnection")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GenerateUuid provides a mock function with no fields
func (_m *Bookmark) GenerateUuid() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GenerateUuid")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// NewBookmark creates a new instance of Bookmark. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewBookmark(t interface {
	mock.TestingT
	Cleanup(func())
}) *Bookmark {
	mock := &Bookmark{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
