// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/PhanNam1501/bookmark-management/internal/model"
	mock "github.com/stretchr/testify/mock"
)

// Repository is an autogenerated mock type for the Repository type
type Repository struct {
	mock.Mock
}

// CreateBookmark provides a mock function with given fields: ctx, b
func (_m *Repository) CreateBookmark(ctx context.Context, b *model.Bookmark) error {
	ret := _m.Called(ctx, b)

	if len(ret) == 0 {
		panic("no return value specified for CreateBookmark")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.Bookmark) error); ok {
		r0 = rf(ctx, b)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteBookmark provides a mock function with given fields: ctx, bookmarkID, userID
func (_m *Repository) DeleteBookmark(ctx context.Context, bookmarkID string, userID string) error {
	ret := _m.Called(ctx, bookmarkID, userID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteBookmark")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, bookmarkID, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetBookmarkByCode provides a mock function with given fields: ctx, code
func (_m *Repository) GetBookmarkByCode(ctx context.Context, code string) (*model.Bookmark, error) {
	ret := _m.Called(ctx, code)

	if len(ret) == 0 {
		panic("no return value specified for GetBookmarkByCode")
	}

	var r0 *model.Bookmark
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*model.Bookmark, error)); ok {
		return rf(ctx, code)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *model.Bookmark); ok {
		r0 = rf(ctx, code)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Bookmark)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, code)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetBookmarkCounts provides a mock function with given fields: ctx, userID
func (_m *Repository) GetBookmarkCounts(ctx context.Context, userID string) (int64, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetBookmarkCounts")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (int64, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) int64); ok {
		r0 = rf(ctx, userID)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// QueryBookmarks provides a mock function with given fields: ctx, userID, limit, offset
func (_m *Repository) QueryBookmarks(ctx context.Context, userID string, limit int, offset int) ([]*model.Bookmark, error) {
	ret := _m.Called(ctx, userID, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for QueryBookmarks")
	}

	var r0 []*model.Bookmark
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int, int) ([]*model.Bookmark, error)); ok {
		return rf(ctx, userID, limit, offset)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, int, int) []*model.Bookmark); ok {
		r0 = rf(ctx, userID, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.Bookmark)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, int, int) error); ok {
		r1 = rf(ctx, userID, limit, offset)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateBookmark provides a mock function with given fields: ctx, bookmarkID, userID, updateData
func (_m *Repository) UpdateBookmark(ctx context.Context, bookmarkID string, userID string, updateData map[string]interface{}) error {
	ret := _m.Called(ctx, bookmarkID, userID, updateData)

	if len(ret) == 0 {
		panic("no return value specified for UpdateBookmark")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, map[string]interface{}) error); ok {
		r0 = rf(ctx, bookmarkID, userID, updateData)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateBookmarkCode provides a mock function with given fields: ctx, bookmarkID, code
func (_m *Repository) UpdateBookmarkCode(ctx context.Context, bookmarkID string, code string) error {
	ret := _m.Called(ctx, bookmarkID, code)

	if len(ret) == 0 {
		panic("no return value specified for UpdateBookmarkCode")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, bookmarkID, code)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewRepository creates a new instance of Repository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *Repository {
	mock := &Repository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
