services:
  postgres:
    image: postgres:16-alpine
    container_name: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./db_data:/var/lib/postgresql
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=admin
      - POSTGRES_DB=bookmark_management
    networks:
      - bookmark_management
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - bookmark_management
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  bookmark_service:
    image: bookmark_service:dev
    container_name: bookmark_service
    env_file:
      - ./bookmark_service/.env
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - bookmark_management

  bookmark_service2:
    image: bookmark_service:dev
    container_name: bookmark_service2
    env_file:
      - ./bookmark_service/.env
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - bookmark_management

  bookmark_service3:
    image: bookmark_service:dev
    container_name: bookmark_service3
    env_file:
      - ./bookmark_service/.env
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - bookmark_management

  # portal:
  #   image: ebnv/bookmark-app-portal:dev
  #   container_name: portal

  nginx:
    image: nginx:alpine
    container_name: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - bookmark_service
      - bookmark_service2
      - bookmark_service3
    networks:
      - bookmark_management


networks:
  bookmark_management:
    driver: bridge